name: Test

on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2.1.6
              env:
                  cache-name: v1-cache-test
              with:
                  path: README.md
                  key: ${{ env.cache-name }}-${{ hashFiles('README.md') }}
